version: "3"
services:

#  nginx:
#    image: webapp-nginx
#    build:
#      context: .
#      dockerfile: Dockerfile-nginx
#    depends_on:
#      - sample_app
#      - image_classifier
#      - ranker
#      - text_classifier_en
#      - text_classifier_ru
#      - text_classifier_es
#      - text_classifier_fr

  sample_app:
    build:
      context: ../sample_app
    ports:
      - 10000:9090

  image_classifier:
    build:
      context: ../image_classifier
    ports:
      - 10001:9090

#  ranker:
#    build:
#      context: ../ranker
#    ports:
#      - 10002:10002
#
  text_classifier_en:
    environment:
      - lang=en
    build:
      context: ../text_classifier
    ports:
      - 10003:9090

  text_classifier_ru:
    environment:
      - lang=ru
    build:
      context: ../text_classifier
    ports:
      - 10004:9090

  text_classifier_fr:
    environment:
      - lang=fr
    build:
      context: ../text_classifier
    ports:
      - 10005:9090

  text_classifier_es:
    environment:
      - lang=es
    build:
      context: ../text_classifier
    ports:
      - 10006:9090
