version: "3.5"
services:

#  nginx:
#    image: webapp-nginx
#    build:
#      context: .
#      dockerfile: Dockerfile-nginx
#    depends_on:
#      - sample_app
#      - image_classifier
#      - ranker
#      - text_classifier_en
#      - text_classifier_ru
#      - text_classifier_es
#      - text_classifier_fr

  sample_app:
    container_name: sample_app
    build:
      context: ../sample_app
    ports:
      - 10000:9090

  image_classifier:
    container_name: image_classifier
    build:
      context: ../image_classifier
      shm_size: '2gb'
    ports:
      - 10001:9090

  ranker:
    container_name: ranker
    build:
      context: ../ranker
    volumes:
      - /home/ubuntu/pyheartex/apps/ranker/data:/app/data
    ports:
      - 10002:9090

  text_classifier_en:
    container_name: text_classifier_en
    environment:
      - lang=en
    build:
      context: ../text_classifier
    ports:
      - 10003:9090

  text_classifier_ru:
    container_name: text_classifier_ru
    environment:
      - lang=ru
    build:
      context: ../text_classifier
    ports:
      - 10004:9090

  text_classifier_fr:
    container_name: text_classifier_fr
    environment:
      - lang=fr
    build:
      context: ../text_classifier
    ports:
      - 10005:9090

  text_classifier_es:
    container_name: text_classifier_es
    environment:
      - lang=es
    build:
      context: ../text_classifier
    ports:
      - 10006:9090

  text_classifier_de:
    container_name: text_classifier_de
    environment:
      - lang=de
    build:
      context: ../text_classifier
    ports:
      - 10007:9090