version: "3"
services:

#  nginx:
#    image: webapp-nginx
#    build:
#      context: .
#      dockerfile: Dockerfile-nginx
#    ports:
#      - 5000:80
#    depends_on:
#      - sample_app
#      - image_classifier

  sample_app:
    build:
      context: ../sample_app

  image_classifier:
    build:
      context: ../image_classifier


#  ranker:
#    build:
#      context: ../ranker
#    ports:
#      - "10002:80"
#
#  text_classifier_en:
#    build:
#      context: ../text_classifier
#      args:
#        lang: en
#    ports:
#      - "10003:80"
#
#  text_classifier_ru:
#    build:
#      context: ../text_classifier
#      args:
#        lang: ru
#    ports:
#      - "10004:80"
#
#  text_classifier_fr:
#    build:
#      context: ../text_classifier
#      args:
#        lang: fr
#    ports:
#      - "10005:80"
#
#  text_classifier_es:
#    build:
#      context: ../text_classifier
#      args:
#        lang: es
#    ports:
#      - "10006:80"